version: "2"

services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: vessel/app:7.3
    ports:
      - "${APP_PORT}:80"
    environment:
      CONTAINER_ENV: "${APP_ENV}"
      XDEBUG_HOST: "${XDEBUG_HOST}"
      WWWUSER: "${WWWUSER}"
    volumes:
      - .:/var/www/html
      - ~/.composer:/home/vessel/.composer
    networks:
      - vessel

  mysql:
    image: mysql:5.7
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - vesselmysql:/var/lib/mysql
      # - ./docker/mysql/conf.d:/etc/mysql/conf.d
      # - ./docker/mysql/logs:/var/log/mysql
    networks:
      - vessel

  redis:
    image: redis:alpine
    volumes:
      - vesselredis:/data
    networks:
      - vessel

networks:
  vessel:
    driver: "bridge"

volumes:
  vesselmysql:
    driver: "local"
  vesselredis:
    driver: "local"
